# https://jaredkhan.com/blog/mypy-pre-commit
repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      name: black
      language_version: python3
      entry: black
      types: [python]
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
#-   repo: https://github.com/timothycrosley/isort
#    rev: 5.7.0
#    hooks:
#    -   id: isort
#-   repo: https://github.com/kynan/nbstripout
#    rev: 0.5.0
#    hooks:
#    -   id: nbstripout
-   repo: local
    hooks:
    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [python]
      args: [--py37-plus]

    -   id: mypy
        name: mypy
        entry: "mypy"
        language: python
        language_version: python3.8.5
        additional_dependencies:
          - "mypy==0.971"
          - "pydantic"
        types: [python]
        args: [--ignore-missing-imports]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # Print the number of files as a sanity-check
        verbose: true



