# Generated by Django 4.0.6 on 2022-07-18 18:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'connect_set',
            },
            managers=[
                ('consets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConnectWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conname', models.CharField(max_length=128, unique=True, verbose_name='Connect name')),
                ('slug_name', models.SlugField(max_length=150)),
                ('engine', models.CharField(choices=[('django.db.backends.sqlite3', 'SQLite connector'), ('src.db.connection.advantage', 'DBF connector'), ('mssql', 'MSSQL connector')], default='django.db.backends.sqlite3', max_length=200, verbose_name='Select engine')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.TextField(verbose_name='NAME')),
                ('options', models.TextField()),
                ('user', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('host', models.CharField(blank=True, max_length=100, verbose_name='HOST')),
                ('port', models.PositiveIntegerField(blank=True, default=0, verbose_name='PORT')),
            ],
            options={
                'db_table': 'connects',
            },
        ),
        migrations.CreateModel(
            name='ImportTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=50, verbose_name='Export table')),
                ('dest_table', models.CharField(max_length=50, verbose_name='Import table')),
                ('message_id', models.UUIDField(blank=True, null=True, verbose_name='Redis message Id')),
                ('uploadable', models.BooleanField(default=True)),
                ('last_write', models.DateTimeField(blank=True, null=True, verbose_name='Last write')),
                ('connects', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connect_sets', to='core.connectset', verbose_name='Select conection set')),
            ],
            options={
                'db_table': 'import_tables',
            },
            managers=[
                ('tables', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='connectset',
            name='dest_conection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dest_conection', to='core.connectwrapper', verbose_name='Select destination conection'),
        ),
        migrations.AddField(
            model_name='connectset',
            name='source_conection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_conection', to='core.connectwrapper', verbose_name='Select source conection'),
        ),
    ]
