# Generated by Django 4.0.6 on 2022-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtables',
            name='upload_record',
            field=models.IntegerField(default=0, verbose_name='Upload'),
        ),
    ]
