# Generated by Django 4.0.6 on 2022-08-18 05:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_connectwrapper_engine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectset',
            options={'verbose_name': '2. Pipeline'},
        ),
        migrations.AlterModelOptions(
            name='connectwrapper',
            options={'verbose_name': '1. Connection list'},
        ),
        migrations.AlterModelOptions(
            name='importtables',
            options={'verbose_name': '3. Pipeline table'},
        ),
        migrations.AlterField(
            model_name='connectwrapper',
            name='conname',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Connect name'),
        ),
        migrations.AlterField(
            model_name='connectwrapper',
            name='engine',
            field=models.CharField(choices=[('src.db.connection.advantage', 'DBF'), ('mssql', 'MSSQL')], default='mssql', max_length=200, verbose_name='Select engine'),
        ),
        migrations.AlterField(
            model_name='connectwrapper',
            name='host',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.validate_ipv4_address], verbose_name='HOST'),
        ),
        migrations.AlterField(
            model_name='connectwrapper',
            name='options',
            field=models.TextField(verbose_name='Connect options'),
        ),
        migrations.AlterField(
            model_name='importtables',
            name='connects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connect_sets', to='core.connectset', verbose_name='Select conection'),
        ),
    ]
