# Generated by Django 4.0.6 on 2022-08-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_connectset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtables',
            name='connects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_sets', to='core.connectset', verbose_name='Select conection'),
        ),
    ]
