# Generated by Django 4.0.6 on 2022-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_importtables_connects'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectset',
            name='type',
            field=models.CharField(choices=[('DBF', 'import from DBF'), ('ARM', 'import from Doc2Sql')], default='DBF', max_length=200, verbose_name='Select import type'),
        ),
    ]
