# Generated by Django 4.0.6 on 2022-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_connectwrapper_host_alter_connectwrapper_port'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectset',
            options={'verbose_name': '#2. Pipeline'},
        ),
        migrations.AlterModelOptions(
            name='connectwrapper',
            options={'verbose_name': '#1. Connection list'},
        ),
        migrations.AlterModelOptions(
            name='importtables',
            options={'verbose_name': '#3. Pipeline table'},
        ),
        migrations.AddField(
            model_name='importtables',
            name='redis_message_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Redis message Id'),
        ),
        migrations.AlterField(
            model_name='importtables',
            name='message_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Broker message Id'),
        ),
        migrations.AlterField(
            model_name='importtables',
            name='uploadable',
            field=models.BooleanField(default=True, verbose_name='Uploadable'),
        ),
    ]
