# Generated by Django 4.0.6 on 2022-10-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dramatiq', '0003_auto_20200204_0842'),
        ('core', '0008_alter_connectset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtables',
            name='message_id',
        ),
        migrations.AddField(
            model_name='importtables',
            name='message',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_dramatiq.task', verbose_name='Broker message Id'),
        ),
        migrations.AlterField(
            model_name='connectset',
            name='type',
            field=models.CharField(choices=[('DBF', 'DBF source'), ('ARM', 'Doc2Sql source')], default='DBF', max_length=200, verbose_name='Select import type'),
        ),
    ]
