# from django.db import models
# # from ..base import import_models
# from src.apps.dbfexport.models import DclHead


# class DclHead(DclHead):
#     g071 = models.CharField(max_length=8, primary_key=True)
#
#     class Meta:
#             managed = False
#             db_table = 'dclhead'
#             unique_together = (('g071', 'g072', 'g073'),)

# class DclHead(BaseModel):
#
#     class Meta(BaseModel.Meta):
#         abstract = True
#         # db_table = 'dclhead'
#
#     num_ver = models.CharField(max_length=8, blank=True, null=True)
#     data_ver = models.DateField(blank=True, null=True)
#     typ_dcl = models.CharField(max_length=2, blank=True, null=True)
#     gugtk = models.BooleanField(blank=True, null=True)
#     copy = models.BooleanField(blank=True, null=True)
#     dcopy = models.DateField(blank=True, null=True)
#     q_edit = models.DecimalField(max_digits=2, decimal_places=0, blank=True, null=True)
#     d_edit = models.DateField(blank=True, null=True)
#     sol = models.DecimalField(max_digits=2, decimal_places=0, blank=True, null=True)
#     max_err = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True)
#     dd = models.DateField(blank=True, null=True)
#     tm = models.CharField(max_length=8, blank=True, null=True)
#     extrnl = models.CharField(max_length=80, blank=True, null=True)
#     schet = models.CharField(max_length=160, blank=True, null=True)
#     stepctrl = models.CharField(max_length=20, blank=True, null=True)
#     typ_dtc = models.CharField(max_length=1, blank=True, null=True)
#     vid_ktc = models.CharField(max_length=1, blank=True, null=True)
#     frm_decl = models.CharField(max_length=1, blank=True, null=True)
#     stat = models.CharField(max_length=1, blank=True, null=True)
#     g071 = models.CharField(max_length=8, blank=True, null=True)
#     g072 = models.DateField(blank=True, null=True)
#     g073 = models.CharField(max_length=7, blank=True, null=True)
#     g073_1 = models.CharField(max_length=6, blank=True, null=True)
#     ui_b_1 = models.CharField(max_length=8, blank=True, null=True)
#     ui_b_2 = models.DateField(blank=True, null=True)
#     ui_b_3 = models.CharField(max_length=7, blank=True, null=True)
#     sds_srv = models.CharField(max_length=4, blank=True, null=True)
#     sds_num = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
#     sds_cust = models.CharField(max_length=8, blank=True, null=True)
#     f_decl = models.CharField(max_length=1, blank=True, null=True)
#     remotepay = models.CharField(max_length=1, blank=True, null=True)
#     rccncode = models.CharField(max_length=2, blank=True, null=True)
#     dpresent = models.DateField(blank=True, null=True)
#     tpresent = models.CharField(max_length=8, blank=True, null=True)
#     complectbl = models.CharField(max_length=1, blank=True, null=True)
#     g011 = models.CharField(max_length=2, blank=True, null=True)
#     g012 = models.CharField(max_length=2, blank=True, null=True)
#     g0121 = models.CharField(max_length=2, blank=True, null=True)
#     g0131 = models.CharField(max_length=3, blank=True, null=True)
#     g020 = models.CharField(max_length=15, blank=True, null=True)
#     g02_itn = models.CharField(max_length=13, blank=True, null=True)
#     g021 = models.CharField(max_length=12, blank=True, null=True)
#     g022 = models.CharField(max_length=150, blank=True, null=True)
#     g023post = models.CharField(max_length=9, blank=True, null=True)
#     g0231 = models.CharField(max_length=2, blank=True, null=True)
#     g0231c = models.CharField(max_length=3, blank=True, null=True)
#     g0231n = models.CharField(max_length=40, blank=True, null=True)
#     g023subd = models.CharField(max_length=50, blank=True, null=True)
#     g023city = models.CharField(max_length=35, blank=True, null=True)
#     g023street = models.CharField(max_length=50, blank=True, null=True)
#     g023build = models.CharField(max_length=50, blank=True, null=True)
#     g023 = models.CharField(max_length=80, blank=True, null=True)
#     g024b = models.CharField(max_length=5, blank=True, null=True)
#     g024n = models.CharField(max_length=10, blank=True, null=True)
#     g024in = models.CharField(max_length=12, blank=True, null=True)
#     g027 = models.CharField(max_length=9, blank=True, null=True)
#     g0281 = models.CharField(max_length=7, blank=True, null=True)
#     g0281a = models.CharField(max_length=25, blank=True, null=True)
#     g02821 = models.CharField(max_length=11, blank=True, null=True)
#     g02822 = models.CharField(max_length=25, blank=True, null=True)
#     g02823 = models.CharField(max_length=150, blank=True, null=True)
#     g0283 = models.DateField(blank=True, null=True)
#     g022a = models.CharField(max_length=150, blank=True, null=True)
#     g027a = models.CharField(max_length=9, blank=True, null=True)
#     g023apost = models.CharField(max_length=9, blank=True, null=True)
#     g0231a = models.CharField(max_length=2, blank=True, null=True)
#     g0231an = models.CharField(max_length=40, blank=True, null=True)
#     g023asubd = models.CharField(max_length=50, blank=True, null=True)
#     g023acity = models.CharField(max_length=35, blank=True, null=True)
#     g023astree = models.CharField(max_length=50, blank=True, null=True)
#     g023abuild = models.CharField(max_length=50, blank=True, null=True)
#     g029 = models.CharField(max_length=1, blank=True, null=True)
#     g02e14 = models.CharField(max_length=1, blank=True, null=True)
#     g032 = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
#     g040 = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
#     g04 = models.DecimalField(max_digits=7, decimal_places=0, blank=True, null=True)
#     g05 = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
#     g06 = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
#     g07 = models.CharField(max_length=3, blank=True, null=True)
#     g080 = models.CharField(max_length=15, blank=True, null=True)
#     g08_itn = models.CharField(max_length=13, blank=True, null=True)
#     g081 = models.CharField(max_length=12, blank=True, null=True)
#     g082 = models.CharField(max_length=150, blank=True, null=True)
#     g083post = models.CharField(max_length=9, blank=True, null=True)
#     g0831 = models.CharField(max_length=2, blank=True, null=True)
#     g0831c = models.CharField(max_length=3, blank=True, null=True)
#     g0831a = models.CharField(max_length=40, blank=True, null=True)
#     g083subd = models.CharField(max_length=50, blank=True, null=True)
#     g083city = models.CharField(max_length=35, blank=True, null=True)
#     g083street = models.CharField(max_length=50, blank=True, null=True)
#     g083build = models.CharField(max_length=50, blank=True, null=True)
#     g083 = models.CharField(max_length=80, blank=True, null=True)
#     g084b = models.CharField(max_length=5, blank=True, null=True)
#     g087 = models.CharField(max_length=9, blank=True, null=True)
#     g0881 = models.CharField(max_length=7, blank=True, null=True)
#     g0881a = models.CharField(max_length=25, blank=True, null=True)
#     g08821 = models.CharField(max_length=11, blank=True, null=True)
#     g08822 = models.CharField(max_length=25, blank=True, null=True)
#     g08823 = models.CharField(max_length=150, blank=True, null=True)
#     g0883 = models.DateField(blank=True, null=True)
#     g089 = models.CharField(max_length=1, blank=True, null=True)
#     g082a = models.CharField(max_length=150, blank=True, null=True)
#     g087a = models.CharField(max_length=9, blank=True, null=True)
#     g083apost = models.CharField(max_length=9, blank=True, null=True)
#     g0831aa = models.CharField(max_length=2, blank=True, null=True)
#     g0831an = models.CharField(max_length=40, blank=True, null=True)
#     g083asubd = models.CharField(max_length=50, blank=True, null=True)
#     g083acity = models.CharField(max_length=35, blank=True, null=True)
#     g083astree = models.CharField(max_length=50, blank=True, null=True)
#     g083abuild = models.CharField(max_length=50, blank=True, null=True)
#     g08e14 = models.CharField(max_length=1, blank=True, null=True)
#     g090 = models.CharField(max_length=15, blank=True, null=True)
#     g09_itn = models.CharField(max_length=13, blank=True, null=True)
#     g091 = models.CharField(max_length=12, blank=True, null=True)
#     g092 = models.CharField(max_length=150, blank=True, null=True)
#     g092a = models.CharField(max_length=150, blank=True, null=True)
#     g093post = models.CharField(max_length=9, blank=True, null=True)
#     g0931 = models.CharField(max_length=2, blank=True, null=True)
#     g0931n = models.CharField(max_length=40, blank=True, null=True)
#     g093subd = models.CharField(max_length=50, blank=True, null=True)
#     g093city = models.CharField(max_length=35, blank=True, null=True)
#     g093street = models.CharField(max_length=50, blank=True, null=True)
#     g093build = models.CharField(max_length=50, blank=True, null=True)
#     g093apost = models.CharField(max_length=9, blank=True, null=True)
#     g0931a = models.CharField(max_length=2, blank=True, null=True)
#     g0931an = models.CharField(max_length=40, blank=True, null=True)
#     g093asubd = models.CharField(max_length=50, blank=True, null=True)
#     g093acity = models.CharField(max_length=35, blank=True, null=True)
#     g093astree = models.CharField(max_length=50, blank=True, null=True)
#     g093abuild = models.CharField(max_length=50, blank=True, null=True)
#     g093 = models.CharField(max_length=80, blank=True, null=True)
#     g093a = models.CharField(max_length=80, blank=True, null=True)
#     g094b = models.CharField(max_length=5, blank=True, null=True)
#     g097 = models.CharField(max_length=9, blank=True, null=True)
#     g097a = models.CharField(max_length=9, blank=True, null=True)
#     g0981 = models.CharField(max_length=7, blank=True, null=True)
#     g0981a = models.CharField(max_length=25, blank=True, null=True)
#     g09821 = models.CharField(max_length=11, blank=True, null=True)
#     g09822 = models.CharField(max_length=25, blank=True, null=True)
#     g09823 = models.CharField(max_length=150, blank=True, null=True)
#     g0983 = models.DateField(blank=True, null=True)
#     g09e14 = models.CharField(max_length=1, blank=True, null=True)
#     g11 = models.CharField(max_length=2, blank=True, null=True)
#     g11c = models.CharField(max_length=3, blank=True, null=True)
#     g12 = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
#     g121 = models.CharField(max_length=3, blank=True, null=True)
#     g12k = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
#     g13 = models.CharField(max_length=8, blank=True, null=True)
#     g140 = models.CharField(max_length=15, blank=True, null=True)
#     g14_itn = models.CharField(max_length=13, blank=True, null=True)
#     g141 = models.CharField(max_length=12, blank=True, null=True)
#     g142 = models.CharField(max_length=150, blank=True, null=True)
#     g142a = models.CharField(max_length=150, blank=True, null=True)
#     g143post = models.CharField(max_length=9, blank=True, null=True)
#     g1431 = models.CharField(max_length=2, blank=True, null=True)
#     g1431n = models.CharField(max_length=40, blank=True, null=True)
#     g143subd = models.CharField(max_length=50, blank=True, null=True)
#     g143city = models.CharField(max_length=35, blank=True, null=True)
#     g143street = models.CharField(max_length=50, blank=True, null=True)
#     g143build = models.CharField(max_length=50, blank=True, null=True)
#     aeorowner = models.CharField(max_length=1, blank=True, null=True)
#     aeocntry = models.CharField(max_length=2, blank=True, null=True)
#     aeonum = models.CharField(max_length=50, blank=True, null=True)
#     aeokind = models.CharField(max_length=1, blank=True, null=True)
#     aeoregcod = models.CharField(max_length=3, blank=True, null=True)
#     g143 = models.CharField(max_length=80, blank=True, null=True)
#     g143apost = models.CharField(max_length=9, blank=True, null=True)
#     g1431a = models.CharField(max_length=2, blank=True, null=True)
#     g1431an = models.CharField(max_length=40, blank=True, null=True)
#     g143asubd = models.CharField(max_length=50, blank=True, null=True)
#     g143acity = models.CharField(max_length=35, blank=True, null=True)
#     g143astree = models.CharField(max_length=50, blank=True, null=True)
#     g143abuild = models.CharField(max_length=50, blank=True, null=True)
#     g143a = models.CharField(max_length=80, blank=True, null=True)
#     g144b = models.CharField(max_length=5, blank=True, null=True)
#     g147 = models.CharField(max_length=9, blank=True, null=True)
#     g147a = models.CharField(max_length=9, blank=True, null=True)
#     g1481 = models.CharField(max_length=7, blank=True, null=True)
#     g1481a = models.CharField(max_length=25, blank=True, null=True)
#     g14821 = models.CharField(max_length=11, blank=True, null=True)
#     g14822 = models.CharField(max_length=25, blank=True, null=True)
#     g14823 = models.CharField(max_length=150, blank=True, null=True)
#     g1483 = models.DateField(blank=True, null=True)
#     g15 = models.CharField(max_length=40, blank=True, null=True)
#     g15a = models.CharField(max_length=2, blank=True, null=True)
#     g15ac = models.CharField(max_length=3, blank=True, null=True)
#     g160 = models.CharField(max_length=1, blank=True, null=True)
#     g16a = models.CharField(max_length=2, blank=True, null=True)
#     g16 = models.CharField(max_length=40, blank=True, null=True)
#     g161 = models.CharField(max_length=2, blank=True, null=True)
#     g17a = models.CharField(max_length=2, blank=True, null=True)
#     g17ac = models.CharField(max_length=3, blank=True, null=True)
#     g17b = models.CharField(max_length=40, blank=True, null=True)
#     g180 = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
#     g182 = models.CharField(max_length=2, blank=True, null=True)
#     g19 = models.CharField(max_length=1, blank=True, null=True)
#     g202 = models.CharField(max_length=3, blank=True, null=True)
#     g2021 = models.CharField(max_length=50, blank=True, null=True)
#     g203 = models.CharField(max_length=250, blank=True, null=True)
#     g210 = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
#     g212 = models.CharField(max_length=2, blank=True, null=True)
#     g221 = models.CharField(max_length=3, blank=True, null=True)
#     g221c = models.CharField(max_length=3, blank=True, null=True)
#     g222 = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
#     g222k = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
#     g23 = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
#     g230 = models.DateField(blank=True, null=True)
#     g231 = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
#     g24 = models.CharField(max_length=3, blank=True, null=True)
#     g270 = models.CharField(max_length=2, blank=True, null=True)
#     g27_itn = models.CharField(max_length=13, blank=True, null=True)
#     g2710 = models.CharField(max_length=1, blank=True, null=True)
#     g271 = models.CharField(max_length=13, blank=True, null=True)
#     g27 = models.CharField(max_length=40, blank=True, null=True)
#     g2711 = models.DateField(blank=True, null=True)
#     g2712 = models.CharField(max_length=8, blank=True, null=True)
#     g2810 = models.CharField(max_length=1, blank=True, null=True)
#     g2811 = models.CharField(max_length=1, blank=True, null=True)
#     g28gtd_1 = models.CharField(max_length=8, blank=True, null=True)
#     g28gtd_2 = models.DateField(blank=True, null=True)
#     g28gtd_3 = models.CharField(max_length=7, blank=True, null=True)
#     g281 = models.CharField(max_length=70, blank=True, null=True)
#     g28zajmb = models.CharField(max_length=70, blank=True, null=True)
#     g281d = models.DateField(blank=True, null=True)
#     g281dd = models.DateField(blank=True, null=True)
#     g2831 = models.CharField(max_length=2, blank=True, null=True)
#     g284 = models.CharField(max_length=50, blank=True, null=True)
#     g284d = models.DateField(blank=True, null=True)
#     g284dd = models.DateField(blank=True, null=True)
#     g28_itn = models.CharField(max_length=13, blank=True, null=True)
#     g28okpo = models.CharField(max_length=10, blank=True, null=True)
#     g28inn = models.CharField(max_length=12, blank=True, null=True)
#     g281oth = models.CharField(max_length=30, blank=True, null=True)
#     g28zajmn = models.CharField(max_length=50, blank=True, null=True)
#     g282 = models.CharField(max_length=70, blank=True, null=True)
#     g28211 = models.CharField(max_length=1, blank=True, null=True)
#     g28212 = models.CharField(max_length=2, blank=True, null=True)
#     g28221 = models.CharField(max_length=3, blank=True, null=True)
#     g28222 = models.CharField(max_length=1, blank=True, null=True)
#     g28230 = models.CharField(max_length=1, blank=True, null=True)
#     g2823 = models.DateField(blank=True, null=True)
#     g28240 = models.CharField(max_length=1, blank=True, null=True)
#     g2824 = models.DateField(blank=True, null=True)
#     g2825 = models.CharField(max_length=3, blank=True, null=True)
#     g30_itn = models.CharField(max_length=13, blank=True, null=True)
#     g300 = models.CharField(max_length=2, blank=True, null=True)
#     g3010 = models.CharField(max_length=1, blank=True, null=True)
#     g30aeoown = models.CharField(max_length=1, blank=True, null=True)
#     g30aeocntr = models.CharField(max_length=2, blank=True, null=True)
#     g301 = models.CharField(max_length=50, blank=True, null=True)
#     g30aeokind = models.CharField(max_length=1, blank=True, null=True)
#     g30aeorcod = models.CharField(max_length=3, blank=True, null=True)
#     g3011 = models.DateField(blank=True, null=True)
#     g30 = models.CharField(max_length=50, blank=True, null=True)
#     g30d = models.DateField(blank=True, null=True)
#     g30post = models.CharField(max_length=9, blank=True, null=True)
#     g30a = models.CharField(max_length=2, blank=True, null=True)
#     g30an = models.CharField(max_length=40, blank=True, null=True)
#     g30subd = models.CharField(max_length=50, blank=True, null=True)
#     g30city = models.CharField(max_length=35, blank=True, null=True)
#     g30street = models.CharField(max_length=50, blank=True, null=True)
#     g30build = models.CharField(max_length=50, blank=True, null=True)
#     g30lname = models.CharField(max_length=150, blank=True, null=True)
#     g3012 = models.CharField(max_length=8, blank=True, null=True)
#     g30121 = models.CharField(max_length=2, blank=True, null=True)
#     g30122 = models.CharField(max_length=50, blank=True, null=True)
#     g4910 = models.CharField(max_length=1, blank=True, null=True)
#     g491 = models.CharField(max_length=30, blank=True, null=True)
#     g492 = models.DateField(blank=True, null=True)
#     g500 = models.CharField(max_length=15, blank=True, null=True)
#     g50_itn = models.CharField(max_length=13, blank=True, null=True)
#     g5011 = models.CharField(max_length=80, blank=True, null=True)
#     g5012 = models.CharField(max_length=80, blank=True, null=True)
#     g5023 = models.CharField(max_length=80, blank=True, null=True)
#     g5033 = models.CharField(max_length=80, blank=True, null=True)
#     g504 = models.CharField(max_length=12, blank=True, null=True)
#     g507 = models.CharField(max_length=9, blank=True, null=True)
#     g5081 = models.CharField(max_length=2, blank=True, null=True)
#     g5081a = models.CharField(max_length=6, blank=True, null=True)
#     g50821 = models.CharField(max_length=11, blank=True, null=True)
#     g50822 = models.CharField(max_length=25, blank=True, null=True)
#     g50823 = models.CharField(max_length=80, blank=True, null=True)
#     g5083 = models.DateField(blank=True, null=True)
#     g54_itn = models.CharField(max_length=13, blank=True, null=True)
#     g5410 = models.CharField(max_length=1, blank=True, null=True)
#     g541 = models.CharField(max_length=14, blank=True, null=True)
#     g541d = models.DateField(blank=True, null=True)
#     g5411 = models.CharField(max_length=50, blank=True, null=True)
#     g5411d = models.DateField(blank=True, null=True)
#     g5411aid = models.CharField(max_length=50, blank=True, null=True)
#     g5411adid = models.CharField(max_length=50, blank=True, null=True)
#     g5411modid = models.CharField(max_length=10, blank=True, null=True)
#     g5411doc = models.CharField(max_length=5, blank=True, null=True)
#     prprov541 = models.CharField(max_length=1, blank=True, null=True)
#     pretype541 = models.CharField(max_length=1, blank=True, null=True)
#     prevnum541 = models.CharField(max_length=50, blank=True, null=True)
#     g541_inn = models.CharField(max_length=12, blank=True, null=True)
#     g541_kpp = models.CharField(max_length=9, blank=True, null=True)
#     g542 = models.DateField(blank=True, null=True)
#     g542t = models.CharField(max_length=8, blank=True, null=True)
#     g5441 = models.CharField(max_length=150, blank=True, null=True)
#     g5441nm = models.CharField(max_length=150, blank=True, null=True)
#     g5441mdnm = models.CharField(max_length=150, blank=True, null=True)
#     g5442 = models.CharField(max_length=50, blank=True, null=True)
#     g5443 = models.CharField(max_length=250, blank=True, null=True)
#     g5444 = models.CharField(max_length=50, blank=True, null=True)
#     g5445 = models.DateField(blank=True, null=True)
#     g544aid = models.CharField(max_length=50, blank=True, null=True)
#     g544adid = models.CharField(max_length=50, blank=True, null=True)
#     g544modid = models.CharField(max_length=10, blank=True, null=True)
#     g544doc = models.CharField(max_length=5, blank=True, null=True)
#     prprov544 = models.CharField(max_length=1, blank=True, null=True)
#     pretype544 = models.CharField(max_length=1, blank=True, null=True)
#     prevnum544 = models.CharField(max_length=50, blank=True, null=True)
#     g5446 = models.DateField(blank=True, null=True)
#     g5447 = models.CharField(max_length=50, blank=True, null=True)
#     g5451 = models.CharField(max_length=7, blank=True, null=True)
#     g5451a = models.CharField(max_length=25, blank=True, null=True)
#     g54521 = models.CharField(max_length=11, blank=True, null=True)
#     g54522 = models.CharField(max_length=25, blank=True, null=True)
#     g54523 = models.CharField(max_length=150, blank=True, null=True)
#     g5453 = models.DateField(blank=True, null=True)
#     g545aid = models.CharField(max_length=50, blank=True, null=True)
#     g545adid = models.CharField(max_length=50, blank=True, null=True)
#     g545modid = models.CharField(max_length=10, blank=True, null=True)
#     g545doc = models.CharField(max_length=5, blank=True, null=True)
#     prprov545 = models.CharField(max_length=1, blank=True, null=True)
#     pretype545 = models.CharField(max_length=1, blank=True, null=True)
#     prevnum545 = models.CharField(max_length=50, blank=True, null=True)
#     gd0 = models.CharField(max_length=2, blank=True, null=True)
#     gd1 = models.DateField(blank=True, null=True)
#     gd11 = models.CharField(max_length=8, blank=True, null=True)
#     gd2 = models.CharField(max_length=4, blank=True, null=True)
#     gd00 = models.CharField(max_length=250, blank=True, null=True)
#     gd01 = models.CharField(max_length=250, blank=True, null=True)
#     gddf = models.DateField(blank=True, null=True)
#     recplatv = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
#     recslotm = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
#     rectrans = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
#     recsumpp = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
#     recpasp = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
#     recusl = models.DecimalField(max_digits=8, decimal_places=0, blank=True, null=True)
#     pprr = models.DecimalField(max_digits=11, decimal_places=2, blank=True, null=True)
#     pprv = models.DecimalField(max_digits=11, decimal_places=2, blank=True, null=True)
#     pposh = models.DecimalField(max_digits=11, decimal_places=2, blank=True, null=True)
#     pnal = models.DecimalField(max_digits=11, decimal_places=2, blank=True, null=True)
#     gnuser = models.CharField(max_length=40, blank=True, null=True)
#     flduser = models.CharField(max_length=40, blank=True, null=True)
#     nrelise = models.CharField(max_length=10, blank=True, null=True)
#     kodtop = models.CharField(max_length=3, blank=True, null=True)
#     g071top = models.CharField(max_length=8, blank=True, null=True)
#     g072top = models.DateField(blank=True, null=True)
#     g073top = models.CharField(max_length=7, blank=True, null=True)
#     typdtop = models.CharField(max_length=2, blank=True, null=True)
#     numdtop = models.CharField(max_length=50, blank=True, null=True)
#     datdtop = models.DateField(blank=True, null=True)
#     fiotop = models.CharField(max_length=40, blank=True, null=True)
#     dattop = models.DateField(blank=True, null=True)
#     dmodify = models.DateField(blank=True, null=True)
#     tmodify = models.CharField(max_length=8, blank=True, null=True)
#     edoc_guid = models.CharField(max_length=32, blank=True, null=True)
#     edoc_id = models.DecimalField(max_digits=19, decimal_places=0, blank=True, null=True)
#     ed_procid = models.CharField(max_length=36, blank=True, null=True)
#     val_contr = models.CharField(max_length=1, blank=True, null=True)
#     ps_contr = models.CharField(max_length=1, blank=True, null=True)
#     p_status1 = models.DecimalField(max_digits=2, decimal_places=0, blank=True, null=True)
#     p_status2 = models.DecimalField(max_digits=2, decimal_places=0, blank=True, null=True)
#     ed_ididkmp = models.CharField(max_length=36, blank=True, null=True)
#     ed_idid = models.CharField(max_length=36, blank=True, null=True)
#     ed_ididcnt = models.CharField(max_length=36, blank=True, null=True)
#     ed_ididftc = models.CharField(max_length=36, blank=True, null=True)
#     xmlvers = models.CharField(max_length=10, blank=True, null=True)
#     typed = models.CharField(max_length=2, blank=True, null=True)
#     # g07x = models.CharField(max_length=23, blank=True, null=True)
