* *********************************************************
* *
* * 06/16/22           TEST_UPSIZE.DBC           13:22:50
* *
* *********************************************************
* *
* * Description:
* * This program was automatically generated by GENDBC
* * Version 2.26.67
* *
* *********************************************************


DisplayStatus([Creating database...])
CLOSE DATA ALL
CREATE DATABASE 'TEST_UPSIZE.DBC'
DisplayStatus([Creating table TEST_TYPES...])
MakeTable_TEST_TYPES()
DisplayStatus([Finished.])

FUNCTION MakeTable_TEST_TYPES
***** Table setup for TEST_TYPES *****
CREATE TABLE 'TEST_TYPES.DBF' NAME 'TEST_TYPES' (ID I NOT NULL AUTOINC NEXTVALUE 2 STEP 1, ;
                         INT I NOT NULL, ;
                         CHAR C(10) NOT NULL, ;
                         CHARBIN C(10) NOCPTRANS NOT NULL, ;
                         CURRENCY Y NOT NULL, ;
                         DATE D NOT NULL, ;
                         DATETIME T NOT NULL, ;
                         DOUBLE B(2) NOT NULL, ;
                         FLOAT F(10, 2) NOT NULL, ;
                         GENERAL G NOT NULL, ;
                         LOGICAL L NOT NULL, ;
                         MEMO M NOT NULL, ;
                         MEMOBIN M NOCPTRANS NOT NULL, ;
                         NUMERIC N(10, 2) NOT NULL, ;
                         VARBINARY Q(10) NOT NULL, ;
                         VARCHAR V(10) NOT NULL, ;
                         VCARCHARB V(10) NOCPTRANS NOT NULL)

***** Create each index for TEST_TYPES *****

***** Change properties for TEST_TYPES *****
ENDFUNC


FUNCTION DisplayStatus(lcMessage)
WAIT WINDOW NOWAIT lcMessage
ENDFUNC
