# Generated by Django 4.0.6 on 2022-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdcldinfo',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tdcltechd',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
