# Generated by Django 4.0.6 on 2022-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlimport', '0003_alter_taktshead_database_alter_taktshead_g07x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdclpk',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
