# Generated by Django 4.0.6 on 2022-12-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlimport', '0004_alter_tdclpk_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdcltovg',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
