# Generated by Django 4.0.6 on 2022-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdtcsscv',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
